### ISSUE TITLE
Support for KiCad V6 ??

### ISSUE THREAD

**Issue by softfoot** [g200kg/kicad-gerberzipper#13]
We use this plugin a lot as it provides a consistent submission to our PCB suppliers.

We are very keen to get a version that runs under V6.

Regards,
Dave

**Comment by g200kg** [comment]
It works fine for me with win11 + KiCad 6.0.2.
Are you having problems?

**Comment by softfoot** [comment]
The only version of the gerberzipper plugin I can find (https://github.com/g200kg/kicad-gerberzipper !!YOURS!!) does not have a json file in the root directory or the correct directory structure for v6 as I understand it.  I bodged one up that works for me, where did you get the version that works for you ???
Dave

**Comment by g200kg** [comment]
I see, I understand.

I copied the plugin directly to the required directory, but you're talking about json data for KiCad 6's "Plugins and Content Manager", right?

I don't currently know the data structure required for "Plugins and Content Manager". I can't find any documentation about this.

If you know, please let me know.

**Comment by g200kg** [comment]
Added support for KiCad 6+ PCM.

Please specify 

`https://raw.githubusercontent.com/g200kg/kicad-pcm-repository/main/repository.json`

as the URL of the repository.

**Comment by softfoot** [comment]
Many thanks
